<template>
  <div class="container-app">
    <h3 class="header-title">
      QUALITY ASSURANCE AND SAFETY REPORT
    </h3>
    <b-row class="mt-4">
      <b-col cols="12" md="6">
        <b-row>
          <b-col cols="3">
            Title
          </b-col>
          <b-col cols="9">
            <b-form-input v-model="title" />
          </b-col>
          <b-col cols="3" class="mt-3">
            Subject
          </b-col>
          <b-col cols="9" class="mt-3">
            <b-form-textarea v-model="subject" />
          </b-col>
          <b-col cols="3" class="mt-3">
            Distribution ('cc' dalam email)
          </b-col>
          <b-col cols="9" class="mt-3">
            <b-form-select
              v-model="distSelected"
              :options="distOptions"
              multiple
              :select-size="4"
            />
          </b-col>
        </b-row>
      </b-col>
      <b-col cols="12" md="6"
        ><b-row>
          <template v-for="r in right">
            <b-col cols="3" class="mb-2">
              {{ r.label }}
            </b-col>
            <b-col cols="9" v-if="r.label !== 'Date'">{{ r.value }}</b-col>
            <b-col cols="9" v-else class="mb-2">
              <datepicker v-model="date" calendar-class="modal-calendar"
            /></b-col> </template
        ></b-row>
      </b-col>
    </b-row>
    <label class="mt-4">I. Introduction</label>
    <ckeditor :editor="editor" v-model="intro" :config="editorConfig" />

    <label class="mt-4">II. Brief Summary</label>
    <ckeditor :editor="editor" v-model="briefSummary" :config="editorConfig" />

    <label class="mt-4">III. Section Summaries</label>
    <br />
    <label>III.1 MLOSA Demographic</label>
    <b-form-textarea placeholder="(Auto generated by system), has filter" />
    <b-row class="mt-4">
      <b-col cols="12" md="9"> <label>III.2 Regression Analysis</label></b-col>
      <b-col cols="12" md="3"
        ><b-form-checkbox
          v-model="checked"
          name="check-button"
          switch
          size="lg"
          class="text-right"
        >
        </b-form-checkbox
      ></b-col>
    </b-row>

    <ckeditor :editor="editor" v-model="regression" :config="editorConfig" />

    <label class="mt-4">III.3 Threat and Error Management Result</label>
    <ckeditor :editor="editor" v-model="threat" :config="editorConfig" />

    <b-row class="mt-4">
      <b-col cols="12" md="9"> <label>IV. Recommendation</label></b-col>
      <b-col cols="12" md="3" class="text-right"
        ><b-button
          variant="primary"
          size="sm"
          @click="
            recommendations = [
              ...recommendations,
              {
                uic: [],
                recommendation: '',
                due_date: '',
                status: ''
              }
            ]
          "
          >Add</b-button
        ></b-col
      >
    </b-row>
    <b-row v-for="r in recommendations" class="mb-3">
      <b-col cols="12" md="8">
        <ckeditor
          :editor="editor"
          v-model="r.recommendation"
          :config="editorConfig"
      /></b-col>
      <b-col cols="12" md="4">
        <label
          >Due Date : <br /><datepicker
            calendar-class="modal-calendar"
            @input="r.due_date = customFormatter($event)"
        /></label>
        <br />
        <label
          >UIC :
          <b-form-select
            v-model="r.uic"
            :options="distOptions"
            multiple
            :select-size="4"
        /></label>
      </b-col>
    </b-row>

    <b-button variant="primary" class="mr-3" @click="postReport('On Progress')"
      >SAVE</b-button
    >
    <b-button variant="success" class="mr-3" @click="postReport('Closed')"
      >SUBMIT</b-button
    >
    <b-button variant="light" class="mr-3" @click="postReport('Open')"
      >CANCEL</b-button
    >

    <b-modal v-model="showModal" centered title="ADD FIELD">
      <b-row>
        <b-col cols="4"> <label class="mt-2">Label</label></b-col>
        <b-col cols="8" class="mb-3">
          <b-form-input v-model="editedData.label" />
        </b-col>
        <b-col cols="4"> <label class="mt-2">Type</label></b-col>
        <b-col cols="8" class="mb-3">
          <b-form-input v-model="editedData.type" /> </b-col></b-row
    ></b-modal>
  </div>
</template>

<script>
import Datepicker from "vuejs-datepicker";
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
import axios from "axios";
import moment from "moment";

export default {
  mounted() {},
  methods: {
    postReport(status) {
      const data = {
        prepared_by: "Test",
        approved_by: "Test",
        checked_by: "Test",
        status,
        title: this.title,
        subject: this.subject,
        report_no: headers.no,
        date: moment(this.date).format("YYYY-MM-DD"),
        attention: "Attention Test",
        issued: "TQY",
        distribution: this.distSelected.map(d => {
          return { name: d };
        }),
        introduction: this.intro,
        brief_summary: this.briefSummary,
        regression_analysis: this.regression,
        threat_error: this.threat,
        recommendations: this.recommendations
      };

      console.log(data);
    },
    MyCustomUploadAdapterPlugin(editor) {
      editor.plugins.get("FileRepository").createUploadAdapter = loader => {
        return new UploadAdapter(loader);
      };
    },
    customFormatter(date) {
      return moment(date).format("YYYY-MM-DD");
    }
  },
  components: { Datepicker },
  data() {
    return {
      title: "",
      subject: "",
      headers: {
        no: null
      },
      editor: ClassicEditor,
      editorData: "<p>Content of the editor.</p>",
      editorConfig: {
        extraPlugins: [this.MyCustomUploadAdapterPlugin]
      },
      date: null,
      dueDate: null,
      showModal: false,
      editedData: {
        label: "",
        type: ""
      },
      right: [
        {
          label: "No",
          value: "(Auto Generate)"
        },
        {
          label: "Date",
          value: "select date"
        },
        {
          label: "Attention",
          value: "auto as recommendation('to' dalam email)"
        },
        {
          label: "Issued",
          value: "TQY"
        },
        {
          label: "Prepared by",
          value: "(Auto Generate)"
        },
        {
          label: "Checked by",
          value: "(Auto Generate)"
        },
        {
          label: "Approved by",
          value: "(Auto Generate)"
        }
      ],
      checked: false,
      distSelected: [],
      distOptions: [
        {
          value: "DT",
          text: "DT"
        },
        {
          value: "DB",
          text: "DB"
        },
        {
          value: "DL",
          text: "DL"
        },
        {
          value: "MQ",
          text: "MQ"
        }
      ],
      intro: null,
      briefSummary: null,
      regression: null,
      threat: null,
      recommendations: [
        { uic: [], recommendation: "", due_date: "", status: "" }
      ]
    };
  }
};

class UploadAdapter {
  constructor(loader) {
    this.loader = loader;
  }

  upload() {
    return this.loader.file.then(uploadedFile => {
      return new Promise((resolve, reject) => {
        const data = new FormData();
        console.log(uploadedFile);
        data.append("upload", uploadedFile);

        // axios({
        //   url: "/index/uploadimage",
        //   method: "post",
        //   data,
        //   headers: {
        //     "Content-Type": "multipart/form-data;"
        //   },
        //   withCredentials: false
        // })
        //   .then(response => {
        //     if (response.data.result == "success") {
        //       resolve({
        //         default: response.data.url
        //       });
        //     } else {
        //       reject(response.data.message);
        //     }
        //   })
        //   .catch(response => {
        //     reject("Upload failed");
        //   });
      });
    });
  }

  abort() {}
}
</script>

<style scoped />
