<template>
  <div class="container-app">
    <h3 class="header-title">
      QUALITY ASSURANCE AND SAFETY REPORT
    </h3>
    <b-row class="mt-4">
      <b-col cols="12" md="6">
        <b-row>
          <b-col cols="3">
            Title
          </b-col>
          <b-col cols="9">
            <b-form-input placeholder="Free text" />
          </b-col>
          <b-col cols="3" class="mt-3">
            Subject
          </b-col>
          <b-col cols="9" class="mt-3">
            <b-form-textarea placeholder="Free Text" />
          </b-col>
          <b-col cols="3" class="mt-3">
            Distribution ('cc' dalam email)
          </b-col>
          <b-col cols="9" class="mt-3">
            <b-form-select
              v-model="distSelected"
              :options="distOptions"
              multiple
              :select-size="4"
            />
          </b-col>
        </b-row>
      </b-col>
      <b-col cols="12" md="6"
        ><b-row>
          <template v-for="r in right">
            <b-col cols="3" class="mb-2">
              {{ r.label }}
            </b-col>
            <b-col cols="9" v-if="r.label !== 'Date'">{{ r.value }}</b-col>
            <b-col cols="9" v-else class="mb-2">
              <datepicker v-model="date"
            /></b-col> </template
        ></b-row>
      </b-col>
    </b-row>
    <label class="mt-4">I. Introduction</label>
    <quill-editor v-model="intro" />
    <label class="mt-4">II. Brief Summary</label>
    <quill-editor v-model="briefSummary" />
    <label class="mt-4">III. Section Summaries</label>
    <br />
    <label>III.1 MLOSA Demographic</label>
    <b-form-textarea placeholder="(Auto generated by system), has filter" />
    <b-row class="mt-4">
      <b-col cols="12" md="9">
        <label
          >III.2 Regression Analysis (Optional as needed. Rich Text, able to
          copy cell from excel)</label
        ></b-col
      >
      <b-col cols="12" md="3"
        ><b-form-checkbox
          v-model="checked"
          name="check-button"
          switch
          size="lg"
          class="text-right"
        >
        </b-form-checkbox
      ></b-col>
    </b-row>
    <quill-editor v-model="regression" />
    <label class="mt-4"
      >III.3 Threat and Error Management Result (berubah menjadi II.2 bila
      regression analysis tidak ada)</label
    >
    <quill-editor v-model="threat" />
    <label class="mt-4">IV. Recommendation</label>
    <b-row>
      <b-col cols="12" md="8"> <quill-editor v-model="recommendation"/></b-col>
      <b-col cols="12" md="4">
        <label>Due Date : <br /><datepicker v-model="dueDate"/></label>
        <br />
        <label
          >UIC :
          <b-form-select
            v-model="distSelected"
            :options="distOptions"
            multiple
            :select-size="4"
        /></label>
      </b-col>
    </b-row>

    <b-button variant="info" class="mr-3">ADD FIELD</b-button>
    <b-button variant="success" class="mr-3">SAVE</b-button>
    <b-button variant="primary">SUBMIT</b-button>
  </div>
</template>

<script>
import Datepicker from "vuejs-datepicker";

export default {
  components: { Datepicker },
  data() {
    return {
      date: null,
      dueDate: null,
      right: [
        {
          label: "No",
          value: "(Auto Generate)"
        },
        {
          label: "Date",
          value: "select date"
        },
        {
          label: "Attention",
          value: "auto as recommendation('to' dalam email)"
        },
        {
          label: "Issued",
          value: "TQY"
        },
        {
          label: "Prepared by",
          value: "(Auto Generate)"
        },
        {
          label: "Checked by",
          value: "(Auto Generate)"
        },
        {
          label: "Approved by",
          value: "(Auto Generate)"
        }
      ],
      checked: false,
      distSelected: null,
      distOptions: [
        {
          value: "DT",
          text: "DT"
        },
        {
          value: "DB",
          text: "DB"
        },
        {
          value: "DL",
          text: "DL"
        },
        {
          value: "MQ",
          text: "MQ"
        }
      ],
      intro: null,
      briefSummary: null,
      regression: null,
      threat: null,
      recommendation: null
    };
  }
};
</script>

<style scoped />
